version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/spyder/desktop/Auth.io
      - node_modules:/home/spyder/desktop/Auth.io/node_modules
    command: npx nodemon index.js

volumes:
  node_modules:
